name: Deploy

on:
  push:
    branches: 
     - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      
      - name: Build
        run: go build
        
      - name: Publish
        uses: appleboy/scp-action@master
        with:
          source: "animenya.site"
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          target: ${{ secrets.SSH_DIR }}
          key: ${{ secrets.SSH_KEY }}
