name: Deploy

on:
  push:
    branches: 
     - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      
      - name: Build
        id: go
        run: go build -v
      
      - run: pwd
      - run: ls
      
      - name: Publish
        if: steps 
        uses: nogsantos/scp-deploy@master
        with:
          src: animenya.site
          host: ${{ secrets.SSH_HOST }}
          remote: ${{ secrets.SSH_DIR }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
